#!/usr/bin/env python3
"""
OpenClaw Memory Wiki - Daily Indexer

Extracts topics, projects, decisions from sessions and updates:
- logbook/YYYY-MM-DD.md (daily log)
- memory/projects/*.md (project knowledge)
- memory/topics/*.md (topic knowledge)
- memory/decisions/*.md (decisions log)
- memory/INDEX.md (master index)

Run daily via cron: 0 2 * * * openclaw-memory-index
"""

import os
import sys
import json
from datetime import datetime, timedelta
from pathlib import Path

# Configuration
WORKSPACE = Path(os.environ.get('OPENCLAW_WORKSPACE', '/Users/openclawassistent/.openclaw/workspace'))
LOGBOOK_DIR = WORKSPACE / 'logbook'
MEMORY_DIR = WORKSPACE / 'memory'
SESSIONS_DIR = WORKSPACE / '.openclaw' / 'sessions'

def get_today():
    return datetime.now().strftime('%Y-%m-%d')

def get_yesterday():
    return (datetime.now() - timedelta(days=1)).strftime('%Y-%m-%d')

def find_new_sessions(since_date):
    """Find all session files since given date"""
    sessions = []
    print(f"🔍 Finding sessions since {since_date}...")
    return sessions

def extract_metadata(session_content):
    """Use LLM to extract topics, projects, decisions from session"""
    print(f"🧠 Analyzing session...")
    return {
        'topics': [],
        'projects': [],
        'decisions': [],
        'action_items': [],
        'learnings': []
    }

def update_logbook(date, sessions):
    """Create/update daily logbook entry"""
    logbook_file = LOGBOOK_DIR / f'{date}.md'
    
    content = f"""# {date} - Daily Log

**Day:** {datetime.strptime(date, '%Y-%m-%d').strftime('%A')}  
**Sessions:** {len(sessions)}  
**Total Time:** TBD

---

## Sessions Today

"""
    
    for session in sessions:
        content += f"""### Session #{session.get('id', '???')} - {session.get('time', 'TBD')} - {session.get('title', 'Untitled')}

**Duration:** {session.get('duration', '?')} min  
**Topics:** {', '.join(session.get('topics', []))}  
**Projects:** {', '.join(session.get('projects', []))}

**Summary:**
{session.get('summary', 'No summary available')}

**Decisions Made:**
"""
        for decision in session.get('decisions', []):
            content += f"- {decision}\n"
        
        content += "\n**Action Items Created:**\n"
        for item in session.get('action_items', []):
            content += f"- [ ] {item}\n"
        
        content += "\n---\n\n"
    
    content += """## Daily Summary

**What got done:**
- TBD

**Blockers:**
- None

**Mood/Energy:**
- TBD

---

*Auto-generated by OpenClaw Memory Wiki*
"""
    
    with open(logbook_file, 'w') as f:
        f.write(content)
    
    print(f"📓 Created {logbook_file}")

def update_memory_project(project_name, session_data):
    """Update or create project memory file"""
    project_file = MEMORY_DIR / 'projects' / f'{project_name}.md'
    
    if not project_file.exists():
        template = (MEMORY_DIR / 'projects' / 'TEMPLATE.md').read_text()
        content = template.replace('[Project Name]', project_name)
        content = content.replace('**Started:** YYYY-MM-DD', f'**Started:** {get_today()}')
        content = content.replace('**Last Updated:** YYYY-MM-DD', f'**Last Updated:** {get_today()}')
        
        with open(project_file, 'w') as f:
            f.write(content)
        
        print(f"🧠 Created project memory: {project_file}")

def update_memory_topic(topic_name, session_data):
    """Update or create topic memory file"""
    topic_file = MEMORY_DIR / 'topics' / f'{topic_name}.md'
    
    if not topic_file.exists():
        template = (MEMORY_DIR / 'topics' / 'TEMPLATE.md').read_text()
        content = template.replace('[Topic Name]', topic_name)
        content = content.replace('**Created:** YYYY-MM-DD', f'**Created:** {get_today()}')
        content = content.replace('**Last Updated:** YYYY-MM-DD', f'**Last Updated:** {get_today()}')
        
        with open(topic_file, 'w') as f:
            f.write(content)
        
        print(f"🏷️ Created topic memory: {topic_file}")

def update_index():
    """Update master INDEX.md"""
    index_file = MEMORY_DIR / 'INDEX.md'
    print(f"📑 Updating INDEX.md...")

def main():
    print("🚀 OpenClaw Memory Wiki - Daily Indexer")
    print("=" * 50)
    
    since_date = get_yesterday()
    sessions = find_new_sessions(since_date)
    
    if not sessions:
        print("✅ No new sessions found. Nothing to index.")
        return
    
    print(f"📊 Found {len(sessions)} sessions to process")
    
    processed_sessions = []
    for session in sessions:
        print(f"\nProcessing session {session.get('id', '???')}...")
        metadata = extract_metadata(session)
        session.update(metadata)
        processed_sessions.append(session)
        
        for project in metadata.get('projects', []):
            update_memory_project(project, session)
        
        for topic in metadata.get('topics', []):
            update_memory_topic(topic, session)
    
    today = get_today()
    update_logbook(today, processed_sessions)
    update_index()
    
    print("\n" + "=" * 50)
    print("✅ Daily indexing complete!")
    print(f"📓 Logbook: {LOGBOOK_DIR / f'{today}.md'}")
    print(f"🧠 Memory: {MEMORY_DIR}")

if __name__ == '__main__':
    main()
